server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

feign:
  hystrix:
    enabled: true